export default function handler(req, res) {

	return res.status(200).json([
		'asac.near',
		'nearton_nft.near',
		'futurenft.near',
		'tinkerunion_nft.enleap.near',
		'grimms.secretskelliessociety.near',
		'nearnautnft.near',
		'secretskelliessociety.near',
		'degenlizard.near',
		'classykangaroos1.near',
		'mrbrownproject.near',
		'boo-monster-by-omarbibznear',
		'im-by-neonzxxxnear',
		'mara-gen-0-by-maranftnear',
		'spectral-by-spectralnear',
		'misfits.tenk.near',
		'lionpride.neartopia.near',
		'classykangaroos1.near',
		'tigeracademy.near',
		'flipped-face-by-taiternnear',
		'nft.thedons.near',
		'nearton_nft.near',
		'thebullishbulls.near',
		'robotics-by-napjarunear',
		'im-by-neonzxxxnear',
		'themetaspace.near',
		'billionairebullsclub.near',
		'kokumokongz.near',
		'dragonnation.near',
		'tayc-nft.near',
		'kaizofighters.tenk.near',
		'sundogz-by-sundogznear',
		'the-nox-by-thenoxnear',
		'the-wooks-by-nearwooksnear',
		'mara-smartcontract.near',
		'tuff-toucans-by-thewildernessnear',
		'nft.havendao.near',
		'623c2cd4294f600e58f46fa2.astrogenfunds.near',
	])


}